# Increase the memory available to Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Configuration cache compatibility with Fabric Loom
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=1.21.1
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=com.dwurdy
archives_base_name=heaphammer

# Dependencies
fabric_api_version=0.116.17+1.21.1
java_version=21
