pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		maven {
			name = 'CleanroomMC'
			url = 'https://maven.cleanroommc.com'
		}
		maven {
			name = 'GTNH'
			url = 'https://nexus.gtnewhorizons.com/repository/public/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

plugins {
	id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

rootProject.name = 'heaphammer'
