modLoader = "javafml"
loaderVersion = "[4,)"
license = "LGPL-3.0"
issueTrackerURL = "https://github.com/DurdeuVlad/heaphammer/issues"

[[mods]]
modId = "heaphammer"
version = "${version}"
displayName = "HeapHammer"
authors = "dwurdy"
description = '''Deterministic stress-testing and retained-memory regression framework for modded Minecraft.'''
logoFile = "assets/heaphammer/icon.png"

[[dependencies.heaphammer]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.heaphammer]]
modId = "minecraft"
type = "required"
versionRange = "${mc_version_range}"
ordering = "NONE"
side = "BOTH"
